renaissance:
    resource: "@RenaissanceBundle/Resources/config/routing.yml"
    prefix:   /renaissance/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
#    resource: "@AppBundle/Controller/ApiController"
    resource: AppBundle\Controller\ApiController
    type:     rest
    prefix:   /api/v1