renaissance:
    resource: "@RenaissanceBundle/Resources/config/routing.yml"
    prefix:   /renaissance/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    type:     rest
    resource: AppBundle\Controller\ApiController
    prefix:   /api/{prefix}
