# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    EntityRepository.ArticleCategory:
        class: Doctrine\ORM\EntityRepository
        # factory_service: doctrine.orm.entity_manager
        # factory_method: getRepository
        factory: ["@doctrine", "getRepository"]
        arguments:
            - AppBundle\Entity\ArticleCategory

    Service.ArticleCategory:
        class: Core\Service\ArticleCategoryProvider
        arguments:
            - "@EntityRepository.ArticleCategory"
