
get_articles:
    path:     /getArticles
    defaults: { _controller: AppBundle:Article:getArticles }

get_article:
    path:     /getArticle
    defaults: { _controller: AppBundle:Article:getArticle }

get_articles:
    path:     /getArticles
    defaults: { _controller: AppBundle:Article:getArticles }

get_article:
    path:     /getArticle
    defaults: { _controller: AppBundle:Article:getArticle }
