AppBundle\Entity\ArticleCategory:
    exclusion_policy: ALL
    properties:
        idArticleCategory:
            expose: true
        name:
            expose: true
        slug:
            expose: true