AppBundle\Entity\News:
    exclusion_policy: ALL
    properties:
        idNews:
            expose: true
        title:
            expose: true
        slug:
            expose: true
        user:
            expose: true
        modificationDate:
            expose: true
