AppBundle\Entity\Article:
    exclusion_policy: ALL
    properties:
        idArticle:
            expose: true
        title:
            expose: true
        slug:
            expose: true
#        category:
#            expose: true