renaissance_homepage:
    path:     /
    defaults: { _controller: RenaissanceBundle:Default:index }


news_index:
    path:     /aktualnosci/ostatnie
    defaults: { _controller: RenaissanceBundle:News:index }

news_archive:
    path:     /aktualnosci
    defaults: { _controller: RenaissanceBundle:News:archive }

news_archive_by_year:
    path:     /aktualnosci/{year}
    defaults: { _controller: RenaissanceBundle:News:archiveByYear }

news_archive_by_month:
    path:     /aktualnosci/{year}/{month}
    defaults: { _controller: RenaissanceBundle:News:archiveByMonth }

news_show:
    path:     /aktualnosci/{year}/{month}/{day}/{title}
    defaults: { _controller: RenaissanceBundle:News:show }


article_index:
    path:     /artykuly
    defaults: { _controller: RenaissanceBundle:Article:index }

article_category:
    path:     /artykuly/{category}
    defaults: { _controller: RenaissanceBundle:Article:category }

article_show:
    path:     /artykuly/{category}/{slug}
    defaults: { _controller: RenaissanceBundle:Article:show }
