renaissance_homepage:
    path:     /
    defaults: { _controller: RenaissanceBundle:Default:index }

_index:
    path:     /artykuly
    defaults: { _controller: RenaissanceBundle:Article:index }

_category:
    path:     /artykuly/{category}
    defaults: { _controller: RenaissanceBundle:Article:category }

_show:
    path:     /artykuly/{category}/{slug}
    defaults: { _controller: RenaissanceBundle:Article:show }
