services:
#    renaissance.example:
#        class: RenaissanceBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    renaissance.service.news:
        class: Core\Service\NewsProvider
        arguments: ["@service_container"]
