services:
#    renaissance.example:
#        class: RenaissanceBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    core.provider.news:
        class: Core\Service\NewsProvider
        arguments: ["@core.repository.news"]
    core.provider.article:
        class: Core\Service\ArticleProvider
        arguments: ["@core.repository.article"]
    core.provider.category:
        class: Core\Service\CategoryProvider
        arguments: ["@core.repository.category"]

    core.repository.user:
        class: Doctrine\ORM\EntityManager
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\User
    core.repository.news:
        class: Doctrine\ORM\EntityManager
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\News
    core.repository.category:
        class: Doctrine\ORM\EntityManager
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\ArticleCategory
    core.repository.article:
        class: Doctrine\ORM\EntityManager
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Article

    core.manager.news:
        class: Core\Service\NewsManager
        arguments: ["@core.repository.news"]
    core.manager.category:
        class: Core\Service\CategoryManager
        arguments: ["@core.repository.category"]
    core.manager.article:
        class: Core\Service\ArticleManager
        arguments: ["@core.repository.article", "@core.repository.category", "@core.repository.user"]
